name: BlockRunner-Remake
main: me.awesomeman2812.BlockRunner.main.BR
version: 0.1
author: AwesomeMan2812
commands:
   br:
      description: This is the main command for BlockRunner.
      usage: /<command>
      permission: blockrunner.default
      permission-message: You don't have permission to use this command!
      aliases: [br,blockrunner,blockrun]
permissions:
   blockrunner.default:
      description: The default permission for all players
      default: true
   blockrunner.vip:
      description: The permission given to VIP players for perks
      default: op
      children:
        - blockrunner.default
   blockrunner.admin:
      description: The permission given to Admin players
      default: op
      children:
        - blockrunner.vip
